
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jun 30 12:32:17 CEST 2016
//----------------------------------------------------

package rholang.parsing.lambda;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int _SYMB_6 = 8;
  public static final int SimpleType = 11;
  public static final int _SYMB_5 = 7;
  public static final int _SYMB_4 = 6;
  public static final int _SYMB_3 = 5;
  public static final int _SYMB_2 = 4;
  public static final int _SYMB_1 = 3;
  public static final int _SYMB_0 = 2;
  public static final int EOF = 0;
  public static final int _STRING_ = 9;
  public static final int error = 1;
  public static final int _INTEGER_ = 10;
  public static final int Var = 12;
}

