package rholang.parsing.delimc.Absyn; // Java Package generated by the BNF Converter.

public class EPushSubCont extends Expr {
  public final Expr expr_1, expr_2;
  public final Type type_;
  public EPushSubCont(Expr p1, Expr p2, Type p3) { expr_1 = p1; expr_2 = p2; type_ = p3; }

  public <R,A> R accept(rholang.parsing.delimc.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.delimc.Absyn.EPushSubCont) {
      rholang.parsing.delimc.Absyn.EPushSubCont x = (rholang.parsing.delimc.Absyn.EPushSubCont)o;
      return this.expr_1.equals(x.expr_1) && this.expr_2.equals(x.expr_2) && this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.expr_1.hashCode())+this.expr_2.hashCode())+this.type_.hashCode();
  }


}
