package rholang.parsing.lambda.Absyn; // Java Package generated by the BNF Converter.

public class EAbs extends Expr {
  public final String var_;
  public final Type type_1, type_2;
  public final Expr expr_;
  public EAbs(String p1, Type p2, Expr p3, Type p4) { var_ = p1; type_1 = p2; expr_ = p3; type_2 = p4; }

  public <R,A> R accept(rholang.parsing.lambda.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.lambda.Absyn.EAbs) {
      rholang.parsing.lambda.Absyn.EAbs x = (rholang.parsing.lambda.Absyn.EAbs)o;
      return this.var_.equals(x.var_) && this.type_1.equals(x.type_1) && this.expr_.equals(x.expr_) && this.type_2.equals(x.type_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.var_.hashCode())+this.type_1.hashCode())+this.expr_.hashCode())+this.type_2.hashCode();
  }


}
