package rholang.parsing.lambda.Absyn; // Java Package generated by the BNF Converter.

public class Tuple3 extends Tuple {
  public final Expr expr_1, expr_2, expr_3;
  public Tuple3(Expr p1, Expr p2, Expr p3) { expr_1 = p1; expr_2 = p2; expr_3 = p3; }

  public <R,A> R accept(rholang.parsing.lambda.Absyn.Tuple.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.lambda.Absyn.Tuple3) {
      rholang.parsing.lambda.Absyn.Tuple3 x = (rholang.parsing.lambda.Absyn.Tuple3)o;
      return this.expr_1.equals(x.expr_1) && this.expr_2.equals(x.expr_2) && this.expr_3.equals(x.expr_3);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.expr_1.hashCode())+this.expr_2.hashCode())+this.expr_3.hashCode();
  }


}
