package parsing.delimc.Absyn; // Java Package generated by the BNF Converter.

public class CCType extends MType {
  public final Type type_1, type_2;
  public CCType(Type p1, Type p2) { type_1 = p1; type_2 = p2; }

  public <R,A> R accept(parsing.delimc.Absyn.MType.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof parsing.delimc.Absyn.CCType) {
      parsing.delimc.Absyn.CCType x = (parsing.delimc.Absyn.CCType)o;
      return this.type_1.equals(x.type_1) && this.type_2.equals(x.type_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.type_1.hashCode())+this.type_2.hashCode();
  }


}
