package parsing.delimc.Absyn; // Java Package generated by the BNF Converter.

public class EAbs extends Expr {
  public final String var_;
  public final Type type_;
  public final Expr expr_;
  public final FType ftype_;
  public EAbs(String p1, Type p2, Expr p3, FType p4) { var_ = p1; type_ = p2; expr_ = p3; ftype_ = p4; }

  public <R,A> R accept(parsing.delimc.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof parsing.delimc.Absyn.EAbs) {
      parsing.delimc.Absyn.EAbs x = (parsing.delimc.Absyn.EAbs)o;
      return this.var_.equals(x.var_) && this.type_.equals(x.type_) && this.expr_.equals(x.expr_) && this.ftype_.equals(x.ftype_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.var_.hashCode())+this.type_.hashCode())+this.expr_.hashCode())+this.ftype_.hashCode();
  }


}
