package parsing.delimc.Absyn; // Java Package generated by the BNF Converter.

public class EPushPrompt extends Expr {
  public final Expr expr_1, expr_2;
  public final MType mtype_;
  public EPushPrompt(Expr p1, Expr p2, MType p3) { expr_1 = p1; expr_2 = p2; mtype_ = p3; }

  public <R,A> R accept(parsing.delimc.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof parsing.delimc.Absyn.EPushPrompt) {
      parsing.delimc.Absyn.EPushPrompt x = (parsing.delimc.Absyn.EPushPrompt)o;
      return this.expr_1.equals(x.expr_1) && this.expr_2.equals(x.expr_2) && this.mtype_.equals(x.mtype_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.expr_1.hashCode())+this.expr_2.hashCode())+this.mtype_.hashCode();
  }


}
