package parsing.delimc.Absyn; // Java Package generated by the BNF Converter.

public class EReturn extends Expr {
  public final Expr expr_;
  public final MType mtype_;
  public EReturn(Expr p1, MType p2) { expr_ = p1; mtype_ = p2; }

  public <R,A> R accept(parsing.delimc.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof parsing.delimc.Absyn.EReturn) {
      parsing.delimc.Absyn.EReturn x = (parsing.delimc.Absyn.EReturn)o;
      return this.expr_.equals(x.expr_) && this.mtype_.equals(x.mtype_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.expr_.hashCode())+this.mtype_.hashCode();
  }


}
