package parsing.delimc.Absyn; // Java Package generated by the BNF Converter.

public abstract class FType implements java.io.Serializable {
  public abstract <R,A> R accept(FType.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(parsing.delimc.Absyn.FunType p, A arg);

  }

}
