package parsing.delimc.Absyn; // Java Package generated by the BNF Converter.

public abstract class MType implements java.io.Serializable {
  public abstract <R,A> R accept(MType.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(parsing.delimc.Absyn.CCType p, A arg);

  }

}
