package parsing.delimc.Absyn; // Java Package generated by the BNF Converter.

public class TFun extends Type {
  public final FType ftype_;
  public TFun(FType p1) { ftype_ = p1; }

  public <R,A> R accept(parsing.delimc.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof parsing.delimc.Absyn.TFun) {
      parsing.delimc.Absyn.TFun x = (parsing.delimc.Absyn.TFun)o;
      return this.ftype_.equals(x.ftype_);
    }
    return false;
  }

  public int hashCode() {
    return this.ftype_.hashCode();
  }


}
