package parsing.delimc.Absyn; // Java Package generated by the BNF Converter.

public class TMonad extends Type {
  public final MType mtype_;
  public TMonad(MType p1) { mtype_ = p1; }

  public <R,A> R accept(parsing.delimc.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof parsing.delimc.Absyn.TMonad) {
      parsing.delimc.Absyn.TMonad x = (parsing.delimc.Absyn.TMonad)o;
      return this.mtype_.equals(x.mtype_);
    }
    return false;
  }

  public int hashCode() {
    return this.mtype_.hashCode();
  }


}
