package parsing.delimc.Absyn; // Java Package generated by the BNF Converter.

public class TSimple extends Type {
  public final String simpletype_;
  public TSimple(String p1) { simpletype_ = p1; }

  public <R,A> R accept(parsing.delimc.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof parsing.delimc.Absyn.TSimple) {
      parsing.delimc.Absyn.TSimple x = (parsing.delimc.Absyn.TSimple)o;
      return this.simpletype_.equals(x.simpletype_);
    }
    return false;
  }

  public int hashCode() {
    return this.simpletype_.hashCode();
  }


}
