package parsing.lambda.Absyn; // Java Package generated by the BNF Converter.

public class ETuple extends Expr {
  public final ListExpr listexpr_;
  public ETuple(ListExpr p1) { listexpr_ = p1; }

  public <R,A> R accept(parsing.lambda.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof parsing.lambda.Absyn.ETuple) {
      parsing.lambda.Absyn.ETuple x = (parsing.lambda.Absyn.ETuple)o;
      return this.listexpr_.equals(x.listexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.listexpr_.hashCode();
  }


}
