package parsing.lambda.Absyn; // Java Package generated by the BNF Converter.

public abstract class Expr implements java.io.Serializable {
  public abstract <R,A> R accept(Expr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(parsing.lambda.Absyn.EVar p, A arg);
    public R visit(parsing.lambda.Absyn.EVal p, A arg);
    public R visit(parsing.lambda.Absyn.EAbs p, A arg);
    public R visit(parsing.lambda.Absyn.EApp p, A arg);
    public R visit(parsing.lambda.Absyn.ETuple p, A arg);

  }

}
