package parsing.lambda.Absyn; // Java Package generated by the BNF Converter.

public class VString extends Value {
  public final String string_;
  public VString(String p1) { string_ = p1; }

  public <R,A> R accept(parsing.lambda.Absyn.Value.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof parsing.lambda.Absyn.VString) {
      parsing.lambda.Absyn.VString x = (parsing.lambda.Absyn.VString)o;
      return this.string_.equals(x.string_);
    }
    return false;
  }

  public int hashCode() {
    return this.string_.hashCode();
  }


}
