package coop.rchain.syntax.rholang.Absyn; // Java Package generated by the BNF Converter.

public class VEnt extends Value {
  public final Entity entity_;
  public VEnt(Entity p1) { entity_ = p1; }

  public <R,A> R accept(coop.rchain.syntax.rholang.Absyn.Value.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.syntax.rholang.Absyn.VEnt) {
      coop.rchain.syntax.rholang.Absyn.VEnt x = (coop.rchain.syntax.rholang.Absyn.VEnt)o;
      return this.entity_.equals(x.entity_);
    }
    return false;
  }

  public int hashCode() {
    return this.entity_.hashCode();
  }


}
